MAX_LENGTH_INGREDIENT_NAME = 128

MAX_LENGTH_INGREDIENT_MEASUREMENT_UNIT = 64

MAX_LENGTH_RECIPE_NAME = 256

MAX_LENGTH_USER_FIRST_NAME = 150

MAX_LENGTH_USER_LAST_NAME = 150

MIN_COOKING_TIME_VALUE = 1

MIN_AMOUNT_VALUE = 1

BASE62_ALPHABET = (
    "0123456789abcdefghijklmnopqrstuvwxyz"
    "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
)

BASE62_DIVIDER = 62
